name: Audit Stack Approval
on:
  workflow_dispatch:

jobs:
  clients-refresh-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pulumi
        uses: pulumi/actions@v5

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Pulumi Preview
        id: preview
        uses: pulumi/actions@v5
        with:
          command: preview
          refresh: 'false'
          stack-name: clients-dev
          work-dir: client
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

      - name: Check Pulumi Changes
        id: check_changes
        run: |
          echo "${{ steps.preview.outputs.output }}" > preview-output.txt
          CHANGES=$(grep -E "to create|to delete|to update|to replace" preview-output.txt || true)

          if [ -n "$CHANGES" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "changes_summary=$CHANGES" >> "$GITHUB_OUTPUT"
            echo "::notice title=Pulumi Change Detected in Client Stack::$CHANGES"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "changes_summary=No changes detected" >> "$GITHUB_OUTPUT"
            echo "::notice title=No Pulumi Changes in Client Stack::No changes detected"
          fi


      - name: Save Preview Output
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          mkdir -p preview-outputs
          echo "Timestamp: $(date)" > preview-outputs/clients-preview.txt
          echo "Commit: ${{ github.sha }}" >> preview-outputs/clients-preview.txt
          echo "Actor: ${{ github.actor }}" >> preview-outputs/clients-preview.txt
          echo "---" >> preview-outputs/clients-preview.txt
          echo "${{ steps.preview.outputs.output }}" >> preview-outputs/clients-preview.txt

      - name: Upload Preview Artifact
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: clients-preview-output
          path: preview-outputs/
          retention-days: 30

  clients-deploy:
    runs-on: ubuntu-latest
    needs: clients-refresh-preview
    if: needs.clients-refresh-preview.outputs.has_changes == 'true'
    permissions:
      contents: read
      id-token: write
      packages: write
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pulumi
        uses: pulumi/actions@v5

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Pulumi Up
        id: deploy
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: clients-dev
          diff: true
          work-dir: client
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True


      # Security: Save deployment output
      - name: Save Deployment Output
        run: |
          mkdir -p deployment-outputs
          echo "Deployment completed at: $(date)" > deployment-outputs/clients-deploy.txt
          echo "Commit: ${{ github.sha }}" >> deployment-outputs/clients-deploy.txt
          echo "Deployed by: ${{ github.actor }}" >> deployment-outputs/clients-deploy.txt
          echo "---" >> deployment-outputs/clients-deploy.txt
          echo "${{ steps.deploy.outputs.output }}" >> deployment-outputs/clients-deploy.txt


      - name: Upload Deployment Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clients-deployment-output
          path: deployment-outputs/
          retention-days: 90


  foundation-refresh-preview:
    runs-on: ubuntu-latest
    needs: [clients-refresh-preview, clients-deploy]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pulumi
        uses: pulumi/actions@v5

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Pulumi Preview
        id: preview
        uses: pulumi/actions@v5
        with:
          command: preview
          refresh: 'false'
          stack-name: foundation-dev
          work-dir: foundation
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

      - name: Check Pulumi Changes
        id: check_changes
        run: |
          echo "${{ steps.preview.outputs.output }}" > preview-output.txt
          CHANGES=$(grep -E "to create|to delete|to update|to replace" preview-output.txt || true)

          if [ -n "$CHANGES" ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "changes_summary=$CHANGES" >> "$GITHUB_OUTPUT"
            echo "::notice title=Pulumi Change Detected in FOUNDATION Stack::$CHANGES"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "changes_summary=No changes detected" >> "$GITHUB_OUTPUT"
            echo "::notice title=No Pulumi Changes in FOUNDATION Stack::No changes detected"
          fi



  foundation-deploy:
    runs-on: ubuntu-latest
    needs: [clients-refresh-preview, clients-deploy, foundation-refresh-preview]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') && needs.foundation-refresh-preview.outputs.has_changes == 'true'
    permissions:
      contents: read
      id-token: write
      packages: write
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pulumi
        uses: pulumi/actions@v5

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Pulumi Up
        id: deploy
        uses: pulumi/actions@v5
        with:
          command: up
          refresh: 'false'
          stack-name: foundation-dev
          work-dir: foundation
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

  platform-refresh-preview:
    runs-on: ubuntu-latest
    needs: [clients-refresh-preview, clients-deploy, foundation-refresh-preview, foundation-deploy]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure')
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      has_changes: ${{ steps.check_changes.outputs.has_changes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pulumi
        uses: pulumi/actions@v5

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Pulumi Preview
        id: preview
        uses: pulumi/actions@v5
        with:
          command: preview
          refresh: 'false'
          stack-name: platform-dev
          work-dir: platform
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True

#      - name: Check Pulumi Changes
#        id: check_changes
#        run: |
#          echo "${{ steps.preview.outputs.output }}" > preview-output.txt
#          CHANGES=$(grep -E "to create|to delete|to update|to replace" preview-output.txt || true)
#
#          if [ -n "$CHANGES" ]; then
#            echo "has_changes=true" >> "$GITHUB_OUTPUT"
#            echo "changes_summary=$CHANGES" >> "$GITHUB_OUTPUT"
#            echo "::notice title=Pulumi Change Detected in PLATFORM Stack::$CHANGES"
#          else
#            echo "has_changes=false" >> "$GITHUB_OUTPUT"
#            echo "changes_summary=No changes detected" >> "$GITHUB_OUTPUT"
#            echo "::notice title=No Pulumi Changes in PLATFORM Stack::No changes detected"
#          fi

      - name: Check Pulumi Changes
        id: check_changes
        run: |
          echo "${{ steps.preview.outputs.output }}" > preview-output.txt
          
          # Look for the changes summary line
          if grep -q "[0-9]+ changes\." preview-output.txt; then
            CHANGES=$(grep -E "(\+ [0-9]+ to create|\- [0-9]+ to delete|~ [0-9]+ to update|[0-9]+ changes\.)" preview-output.txt | tr '\n' ' ')
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            echo "changes_summary=$CHANGES" >> "$GITHUB_OUTPUT"
            echo "::notice title=Pulumi Changes Detected in PLATFORM Stack::$CHANGES"
          else
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo "changes_summary=No changes detected" >> "$GITHUB_OUTPUT"
            echo "::notice title=No Pulumi Changes in PLATFORM Stack::No changes detected"
          fi
  platform-deploy:
    runs-on: ubuntu-latest
    needs: [ clients-refresh-preview, clients-deploy, foundation-refresh-preview, platform-refresh-preview ]
    if: always() && !cancelled() && !contains(needs.*.result, 'failure') && needs.platform-refresh-preview.outputs.has_changes == 'true'
    permissions:
      contents: read
      id-token: write
      packages: write
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Pulumi
        uses: pulumi/actions@v5

      - name: gcloud authentication
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_DEV }}

      - name: Install gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: NPM install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install

      - name: Pulumi Up
        id: deploy
        uses: pulumi/actions@v5
        with:
          command: up
          refresh: 'false'
          stack-name: platform-dev
          work-dir: platform
          diff: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          USE_GKE_GCLOUD_AUTH_PLUGIN: True